Added Email button for the event list page
City-of-Helsinki/linkedcomponents-ui pull request #182
Opened 2023-05-26 08:35 UTC by arpargo

## Description :sparkles:
Send Email button to send notification information to event creator in the event listing page.

## Issues :bug:
The email information has to be parsed from the createdBy string which usually contains email address. There is potential that if the createdBy field is malformed that this feature does not work.

### Closes :no_good_woman:

**[LINK-1266](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1266):**

2023-05-26 08:50 UTC, jorilindell requested changes
Code looks good. Added couple of comments about unit tests and missing translations. At least translations should be fixed.

2023-05-26 08:50 UTC, jorilindell commented on src/domain/app/i18n/fi.json
> +        "warningNoEmailFound": "Could not find email address linked to this event"
Finnish translation missing

2023-05-26 08:50 UTC, jorilindell commented on src/domain/app/i18n/sv.json
> +        "warningNoEmailFound": "Could not find email address linked to this event"
Swedish translation missing

2023-05-26 08:50 UTC, jorilindell commented on src/domain/event/utils.ts
> +  }
Could add a unit test to test that warning is shown if email is not found from created by attribure

2023-05-26 08:50 UTC, jorilindell commented on src/domain/event/utils.ts
> +};
Could add a unit test to test that created by is parsed correctly

2023-05-26 08:50 UTC, jorilindell commented on src/domain/events/eventActionsDropdown/EventActionsDropdown.tsx
> +  };
Could add a unit test to test that sendEmail + window.location.href functions are called with correct values.

2023-05-26 09:19 UTC, mikkojamG reviewed
Well done, works very nicely 👌 Left couple of comments

2023-05-26 09:19 UTC, mikkojamG commented on src/domain/event/utils.ts
> +  const { isDraft, publisher, createdBy } = event
It looks like this createBy constant is not actually used 🤔

2023-05-26 09:19 UTC, mikkojamG commented on src/domain/event/utils.ts
> +  return false;
This return appears to be unreachable, probably should be moved to default case of the switch statement 🤔

2023-05-26 09:19 UTC, mikkojamG commented on src/domain/event/utils.ts
> +  return createdBy !== (null || undefined || '' || ' - ');
I think we would have the same effect with `return Boolean(createdBy) || createdBy !== ' - '` 🤔

2023-05-26 09:19 UTC, mikkojamG commented on src/domain/event/utils.ts
> +  if (noEmailFound && action == EVENT_ACTIONS.SEND_EMAIL) {
eslint warns should have triple equaliser here, `action === EVENT_ACTIONS.SEND_EMAIL`

2023-05-26 09:19 UTC, mikkojamG commented on src/domain/events/eventActionsDropdown/EventActionsDropdown.tsx
> +    if (event.createdBy != null && event.createdBy != undefined) {
I think `if (event.created) {...}` would give the same effect

2023-05-26 09:19 UTC, mikkojamG commented on src/domain/events/eventActionsDropdown/EventActionsDropdown.tsx
> +    window.location.href =
`mailto:${targetEmail}?subject=${getLocalisedString(event.name, locale)}` would also give the same effect 🤔

2023-06-02 08:32 UTC, mikkojamG approved these changes
LGTM ✅

2023-06-02 12:46 UTC, jorilindell approved these changes
LGTM

2023-06-05 12:42 UTC, merged