Feature/LINK-1774 keyclock authentication
City-of-Helsinki/linkedcomponents-ui pull request #303
Opened 2023-12-28 12:28 UTC by arpargo

DRAFT!

2024-01-03 11:08 UTC, jorilindell requested changes
Generally looks good. Added some improvement ideas. At least failing tests should be fixed

2024-01-03 11:08 UTC, jorilindell commented on src/domain/app/header/Header.tsx
> +  }, [authUser, authenticated]);
This change breaks unit tests in `src/domain/app/header/__tests__/Header.test.tsx` file.
You can fix failing tests by changing
```
import {
  mockedRegistrationUserResponse,
  mockedRegularUserResponse,
  mockedUserResponse,
  mockedUserWithoutOrganizationsResponse,
  userFirstName,
} from '../../../user/__mocks__/user';

...

const findUserMenuButton = () =>
  screen.findByRole('button', { name: userFirstName }, { timeout: 10000 });
``` 
to
```
import {
  mockedRegistrationUserResponse,
  mockedRegularUserResponse,
  mockedUserResponse,
  mockedUserWithoutOrganizationsResponse,
  userName,
} from '../../../user/__mocks__/user';

...

const findUserMenuButton = () =>
  screen.findByRole('button', { name: userName }, { timeout: 10000 });
```

2024-01-03 12:26 UTC, timwessman commented on src/domain/app/header/Header.tsx
> +  }, [authUser, authenticated]);
Thanks, good small improvement

2024-01-03 12:27 UTC, timwessman commented on src/domain/auth/constants.ts
> +    audiences: ['linkedcomponents-ui-dev', 'profile-api-dev'],
Good, let's skip the profile api token

2024-01-03 12:28 UTC, timwessman commented
Thanks for good PR comments, I commited the fixes

2024-01-03 14:59 UTC, jorilindell approved these changes

2024-01-04 10:35 UTC, jorilindell commented on README.md
> +Clone the repository (https://github.com/City-of-Helsinki/linkedevents). Follow the instructions for running linkedevents with docker. Before running `docker compose up` use the `env.example` templat
Authentication between UI and API doesn't work with default env.example values. You could change this to 
```
Clone the repository (https://github.com/City-of-Helsinki/linkedevents). Follow the instructions for running linkedevents with docker. Before running `docker compose up` use the `env.example` template as base for `/docker/django/.env` and add following variables:

- TOKEN_AUTH_ACCEPTED_AUDIENCE=linkedevents-api-dev
- TOKEN_AUTH_AUTHSERVER_URL=https://tunnistus.test.hel.ninja/auth/realms/helsinki-tunnistus
```

2024-01-04 11:35 UTC, merged