LINK-1888 | 3/4 Create price group page
City-of-Helsinki/linkedcomponents-ui pull request #346
Opened 2024-02-29 11:56 UTC by jorilindell

## Description :sparkles:

## Issues :bug:

### Closes :no_good_woman:

**[DEV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/DEV-XXX):**

### Related :handshake:

## Testing :alembic:

### Automated tests :gear:️

### Manual testing :construction_worker_man:

## Screenshots :camera_flash:

## Additional notes :spiral_notepad:

2024-02-29 12:36 UTC, terovirtanen commented
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr346-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-02-29 12:41 UTC, terovirtanen commented
## e2e tests result is __success__ for https://linkedcomponents-pr346-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-03-12 09:11 UTC, harriris-vincit commented
Got a JS error and an empty page when I first created a new price group and then deleted it using the table action.

2024-03-12 09:15 UTC, harriris-vincit requested changes
Got a JS error and an empty page when I first created a new price group and then deleted it using the table action. Need to fix the bug.

2024-03-12 14:01 UTC, jorilindell commented
> Got a JS error and an empty page when I first created a new price group and then deleted it using the table action. Need to fix the bug.

I'm assuming that the reason for this bug is that the only price group from the last page is deleted and after that API return 404 error and response meta data is not found. I fixed this for price groups by redirecting user to page 1 after delete. This same issue should be fixed to other tables as well. But I will create a separate ticket for that.

2024-03-13 14:33 UTC, harriris-vincit commented on src/domain/places/placeList/PlaceList.tsx
> +    meta: placesData?.places?.meta,
This seems a bit unrelated to the price group changes so perhaps could be in its own commit?

2024-03-13 14:34 UTC, harriris-vincit approved these changes
Suggested adding some changes to their own commit, but otherwise looks good to me.

2024-03-14 14:20 UTC, merged