LINK-2046 | filter events by event status
City-of-Helsinki/linkedcomponents-ui pull request #408
Opened 2024-06-10 11:25 UTC by jorilindell

## Description
Add dropdown to event search panel to filter events by the event status.

## Closes
[LINK-2046](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2046)

## Screenshots
<img width="1451" alt="Screenshot 2024-06-10 at 14 15 20" src="https://github.com/City-of-Helsinki/linkedcomponents-ui/assets/24706814/0f6200a7-e178-4d7a-9bc9-b56bc97c5532">

<img width="1432" alt="Screenshot 2024-06-10 at 14 15 47" src="https://github.com/City-of-Helsinki/linkedcomponents-ui/assets/24706814/db2995bb-6172-4f5b-a924-8a1f030d1699">

2024-06-10 11:44 UTC, terovirtanen commented
## e2e tests result is __success__ for https://linkedcomponents-pr408-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-06-18 13:31 UTC, harriris-vincit commented on src/domain/app/i18n/sv.json
> +      "labelEventStatus": "Evenemang status",
```suggestion
      "labelEventStatus": "Evenemangets status",
```

2024-06-18 13:50 UTC, harriris-vincit requested changes
It appears that the event status filter selection is not remembered like, for example, the publisher selection is: when opening an event for editing and returning to the published events list, the event status selection is back to the default state (= empty selection).

2024-06-19 13:23 UTC, terovirtanen commented
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr408-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-06-19 13:27 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://linkedcomponents-pr408-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-06-19 14:14 UTC, jorilindell commented on src/domain/app/i18n/sv.json
> +      "labelEventStatus": "Evenemang status",
Changed as suggested

2024-06-19 14:15 UTC, jorilindell commented
> It appears that the event status filter selection is not remembered like, for example, the publisher selection is: when opening an event for editing and returning to the published events list, the event status selection is back to the default state (= empty selection).

Good catch. The event status value was not initialised in the first load. Added an initial value for eventStatus and the bug should be fixed.

2024-06-19 14:26 UTC, terovirtanen commented
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr408-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-06-19 14:30 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://linkedcomponents-pr408-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-06-20 07:45 UTC, harriris-vincit approved these changes
Can confirm that now the event status filters are remembered. LGTM :+1:

2024-06-20 08:20 UTC, merged