LINK-2065 | add 25.5% as new vat option
City-of-Helsinki/linkedcomponents-ui pull request #416
Opened 2024-06-22 12:18 UTC by jorilindell

## Description
Add 25.5% as new vat option

## Closes
[LINK-2065](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2065)

2024-06-22 12:32 UTC, terovirtanen commented
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr416-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-06-22 12:35 UTC, terovirtanen commented
## e2e tests result is __success__ for https://linkedcomponents-pr416-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-06-26 09:46 UTC, harriris-vincit approved these changes
One comment about the label value of the new VAT %, but otherwise looks really good.

2024-06-26 13:28 UTC, terovirtanen commented
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr416-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-06-26 13:30 UTC, jorilindell commented on src/domain/priceGroup/hooks/useVatOptions.ts
> +    label: `${vat.toFixed(2)} %`,
I changed label to use `toLocaleString` instead of fixed decimals.

2024-06-26 13:31 UTC, terovirtanen commented
## e2e tests result is __success__ for https://linkedcomponents-pr416-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-08-21 08:36 UTC, harriris-vincit requested changes
After recent discussions and planning, the 24 % VAT option should be removed completely.

2024-08-26 09:19 UTC, terovirtanen commented
**LINKEDCOMPONENTS-UI branch is deployed to platta: https://linkedcomponents-pr416-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-08-26 09:26 UTC, terovirtanen commented
## e2e tests result is __failed__ for https://linkedcomponents-pr416-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-08-26 10:01 UTC, harriris-vincit approved these changes
@mikkojamG LGTM :+1: This can be merged now since the 25,5 % support has just been added to the back-end as well.

2024-08-26 10:26 UTC, terovirtanen commented
## e2e tests result is __success__ for https://linkedcomponents-pr416-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-08-26 10:37 UTC, merged